### ISSUE TITLE
nats caddy 

### ISSUE THREAD

**Issue by gedw99** [infogulch/xtemplate#1]
this might match up with your TODO requirements ?

https://github.com/sandstorm/caddy-nats-bridge

**Comment by infogulch** [comment]
I didn't know about that thanks for the reference.

I'm still not exactly sure how I want the integration to go. But basically I'd like some way to do live updates to an htmx page with SSE or websockets.

**Comment by gedw99** [comment]
the caddy-nats-bridge is definitely not for what you want then.

You might like this one as it's designed to work with Pub sub systems.  I use it because it supports web and fat golang apps.  So she and http is all I need for networking then. 

https://github.com/tmaxmax/go-sse#implementing-a-server

**Comment by infogulch** [comment]
I'd like to do it all within a template definition if possible, loosely basing it on this guide: https://thedevelopercafe.com/articles/server-sent-events-in-go-595ae2740c7a

```html
{{define "SSE:GET /events"}}
{{$userid := .Req.Header.Get "Remote-User"}}
{{range $msg := .Subscribe (printf "user.%s.feed_counts" $userid)}}
id: {{$msg.Id}}
data: {{.Template "feed_count_component" ($msg) | toJson}}
{{-.Flush}}
{{end}}
{{end}}
```

This might require a different buffering strategy compared to what xtemplate does today.

**Comment by gedw99** [comment]
sounds good

**Comment by infogulch** [comment]
SSE is implemented now. You can see some examples in the integration/templates directory if you're curious what it looks like:

[sse.html](https://github.com/infogulch/xtemplate/blob/master/integration/templates/sse.html)

[hotreload.html](https://github.com/infogulch/xtemplate/blob/master/integration/templates/hotreload.html)

**Comment by gedw99** [comment]
https://github.com/charbonnierg/caddy-nats for nats does auth call out

**Comment by infogulch** [comment]
It's been a minute, but I pushed an early version of the nats provider to the `next` branch, along with the skeleton of an IM demo:

https://github.com/infogulch/xtemplate/blob/next/test/templates/nats/index.html

<img src="https://github.com/infogulch/xtemplate/assets/133882/334f12a0-4c34-469b-91ad-dbbf43f4fdbf" width=50% height=50%>

**Comment by gedw99** [comment]
> It's been a minute, but I pushed an early version of the nats provider to the `next` branch, along with the skeleton of an IM demo:
> 
> https://github.com/infogulch/xtemplate/blob/next/test/templates/nats/index.html
> 
> <img alt="" width="50%" height="50%" src="https://private-user-images.githubusercontent.com/133882/319078162-334f12a0-4c34-469b-91ad-dbbf43f4fdbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDM2MDQsIm5iZiI6MTcxMjE0MzMwNCwicGF0aCI6Ii8xMzM4ODIvMzE5MDc4MTYyLTMzNGYxMmEwLTRjMzQtNDY5Yi05MWFkLWRiYmY0M2Y0ZmRiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxMTIxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjcyYjhiYzI3ZTY0ZTIyYWVhZWRhNTE4MTdkZmQ4MjM0ZjI5YjI5MmFjMDY2YTVmZDA0YmNiOTViMWI5N2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.18DmTinPcXb7pv06_rNX5E9PlyeNlkiS5t8_TZSqSkc">

this looks like a really great start. I will have a play with this tonight.

**Comment by infogulch** [comment]
The latest release adds nats and natskv providers, so I'm closing as completed. 🎉

I'm curious to hear feedback about it.

**Comment by infogulch** [comment]
The way this is implemented makes it impossible to configure a nats kv and nats conn that use the same internal server from json or cli config. Not sure how to resolve this.
