### ISSUE TITLE
Add a decent Task file / Make file and example

### ISSUE THREAD

**Issue by gedw99** [infogulch/xtemplate#18]
Its a way for devs to try before they buy :)

I had to make one to get going with this project, so why not include one in the project with a simple example ?

**Comment by gedw99** [comment]
https://github.com/infogulch/xrss seems to be a decent example ?

**Comment by gedw99** [comment]
There is a way to compile caddy with a caddy module without using xcaddy. 
I would like to add this to the Makefile also.

Its makes it very easy to work.

**Comment by gedw99** [comment]
We have the caddy cmd now.

so closing here . 

Don’t know about you but combining Xtemplate repo and caddy-Xtemplate into a single repo with a go.work will imho make it easier to work on and manage dependencies. I use this approach quite a lot.

the make file can then do both builds etc too. 

Anyways let me know how you feel about that idea. I can also add a github action that does the build off the make file for Windows, Mac and Linux. Done it many times - works great

**Comment by infogulch** [comment]
I made it a separate repo before I realized that go.mod dependencies of a root module don't necessarily leak into dependents if only a submodule uses it. I may reconsider this.

Do you think a makefile is really necessary? AFAIK there are only a handful of commands required besides the build script in the github workflow dir.

**Comment by gedw99** [comment]
I use go.work file. It’s been awesome to do mono repos.

makefile is good so devs can quickly see how to do things. It task file. Not having one seems silly when every developer needs to run the same things. Also it’s possible to run the makefile in ci in GitHub actions. So one source of truth .

**Comment by gedw99** [comment]
You’re right it’s not need at all .

closing
