### ISSUE TITLE
caddy add package support.

### ISSUE THREAD

**Issue by gedw99** [infogulch/xtemplate#19]
in the latest tagged caddy you dont need to use xacddy.

Instead you can use the package cmd calls like below.

works for me :) Might be a good one for xtemplate ?

It will take ANY caddy and recompile it to have the package inside. 

```make
caddy-run-package-add:
	$(CADDY_RUN_CMD) add-package -h
	$(CADDY_RUN_CMD) add-package $(CADDY_RUN_VAR_PACKAGE)
	

	#$(CADDY_RUN_CMD) add-package github.com/Odyssey346/ListenCaddy
	#$(CADDY_RUN_CMD) add-package github.com/abiosoft/caddy-exec
	#$(CADDY_RUN_CMD) add-package github.com/greenpau/caddy-git
caddy-run-package-del:
	$(CADDY_RUN_CMD) remove-package github.com/Odyssey346/ListenCaddy
	$(CADDY_RUN_CMD) remove-package github.com/abiosoft/caddy-exec
caddy-run-package-ls:
	$(CADDY_RUN_CMD) list-modules --packages
```

**Comment by francislavoie** [comment]
> in the latest tagged caddy you dont need to use xacddy.

But you still should, if possible. `caddy add-package` downloads from https://caddyserver.com/download which has no uptime guarantees. If this is for automation at all, you should avoid it. `add-package` is specifically meant for manual usage (individual end-users), not automation.

**Comment by infogulch** [comment]
Recommending xcaddy seems to be the way. I'll update the readme to reflect this soon. Thanks all for your input. :)

**Comment by infogulch** [comment]
I looked at moving the caddy-xtemplate package into a subdirectory/package of the Go module in this repo, but it looks like caddy packages must be the root Go package in a Go module, so this won't work. Is this correct @francislavoie ?

**Comment by francislavoie** [comment]
No, they can be in subdirectories, you just need to make their package name (in your go.mod) match. For example https://github.com/RussellLuo/caddy-ext has multiple plugins organized that way (I don't necessarily agree though, there's advantages to having it one per repo)
