### ISSUE TITLE
Task file or makefile 

### ISSUE THREAD

**Issue by gedw99** [infogulch/xtemplate#20]
How do you feel about a decent task file to make it easy to run everything ?

I mention this because it will make it easier to add other things as we go , knowing the task file makes it easy or a dev to hit the ground running …

make files are great but I like the idea of task because it works out of the box on any OS , just like caddy

**Comment by infogulch** [comment]
I ended up writing it in cue. We can discuss it here: https://github.com/infogulch/xtemplate/discussions/24
